<a href="https://colab.research.google.com/github/Murtiza007/Supervised-Machine-Learning-Algorithms/blob/main/SML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#SML---#labelled learning
##  2 types-- Regression and classification

#Regresssion---output from the algorithm is in the form of range or continous values or non discerete(non categorical)
#classification--output from the algo will be in categorical form and non continuos (discrete)


#Linear Regression algorithm
#it is the type of relationship in which there this a linear realation(y=mx+c) between on dependent value
#and one or many independent values

# simple LR= Linear relation bw one dependent(y) and one independent value(x) (sal--- experience)
# multiple LR= Linear relation bw one dependent(y) and two or many independent value(x) (sal--- experience,qual,age)
# polynomail R=NON - Linear relation bw one dependent(y) and two or many independent value(x) (sal--- experience,age)

# LR algo(SLR,MLR,PR)

In [ ]:
import pandas as pd
data=pd.read_csv('1000_Companies.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
x=data.iloc[:,[0,1,2,3]].values
y=data.iloc[:,4].values
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       ...,
       [100275.47, 241926.31, 227142.82, 'California'],
       [128456.23, 321652.14, 281692.32, 'California'],
       [161181.72, 270939.86, 295442.17, 'New York']], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

x[:,3]=lb.fit_transform(x[:,3])

x.shape

(1000, 4)

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train.shape
x_test.shape

(200, 4)

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
accuracy=lr.score(x_test,y_test)
accuracy

0.9112595959622045

In [ ]:
a=lr.predict(x_test)
a.shape

(200,)

In [ ]:
new_data=[60000,	800000,	40000,	'California']
new_data[3]=lb.fit_transform([new_data[3]])[0]
predict=lr.predict([new_data])
print("the net profit=",predict)

the net profit= [660367.5518617]


In [ ]:
# decion tree algorithm

import pandas as pd
data=pd.read_csv('Position_Salaries.csv')
data.head()
data.shape

(100, 3)

In [ ]:
x=data.iloc[:,1].values
y=data.iloc[:,2].values


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor()

regressor.fit(x_train.reshape(-1,1),y_train)

DecisionTreeRegressor()

In [ ]:
a=regressor.score(x_test.reshape(-1,1),y_test)
a

1.0

In [ ]:
regressor.predict([[6.5]])

array([150000.])

In [ ]:
#forest Tree Classification

import pandas as pd
data=pd.read_csv('Iris.csv')

data.shape
data.value_counts('Species')
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
x=data.iloc[:,1:5].values
y=data.iloc[:,5].values
x,y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [ ]:
from sklearn.preprocessing import LabelBinarizer
lb=LabelBinarizer()
y=lb.fit_transform(y)


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=50)
classifier.fit(x_train,y_train)

RandomForestClassifier(n_estimators=50)

In [ ]:
accuracy=classifier.score(x_test,y_test)
accuracy

1.0

In [ ]:
new_data=[4.9,	3.0	,1.4,	0.2	]
predict=classifier.predict([new_data])

if (predict[0]==[1,0,0]).all():
  print('setosa')
elif (predict==[0,1,0]).all():
  print('versicolor')
elif (predict==[0,0,1]).all():
  print('virginica')
else:
  print('unkown species')

setosa


In [ ]:
#decision tree classifier

import pandas as pd
data=pd.read_csv('diabetes.csv')

data.shape
data.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
x=data.drop(['Outcome'],axis=1).values
y=data['Outcome'].values


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_test.shape

(154, 8)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
from sklearn.metrics import accuracy_score
accuracy=classifier.score(x_test,y_test)
accuracy

0.7857142857142857

In [ ]:
new_data=[0,	137,	40,	35	,168,	43.1,	2.288	,33	]
result=classifier.predict([new_data])
result

array([1])

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred=classifier.predict(x_test)

cm=confusion_matrix(y_test,y_pred)
cm

array([[89, 18],
       [15, 32]])

In [ ]:
#Foresrt tree regression
import pandas as pd
data=pd.read_csv('cardekho.csv')
data.head()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   name                8128 non-null   object 
 1   year                8128 non-null   int64  
 2   selling_price       8128 non-null   int64  
 3   km_driven           8128 non-null   int64  
 4   fuel                8128 non-null   object 
 5   seller_type         8128 non-null   object 
 6   transmission        8128 non-null   object 
 7   owner               8128 non-null   object 
 8   mileage(km/ltr/kg)  7907 non-null   float64
 9   engine              7907 non-null   float64
 10  max_power           7913 non-null   object 
 11  seats               7907 non-null   float64
dtypes: float64(3), int64(3), object(6)
memory usage: 762.1+ KB


In [ ]:
x=data.drop(['selling_price'],axis=1).values
y=data['selling_price'].values
x

array([['Maruti Swift Dzire VDI', 2014, 145500, ..., 1248.0, '74', 5.0],
       ['Skoda Rapid 1.5 TDI Ambition', 2014, 120000, ..., 1498.0,
        '103.52', 5.0],
       ['Honda City 2017-2020 EXi', 2006, 140000, ..., 1497.0, '78', 5.0],
       ...,
       ['Maruti Swift Dzire ZDi', 2009, 120000, ..., 1248.0, '73.9', 5.0],
       ['Tata Indigo CR4', 2013, 25000, ..., 1396.0, '70', 5.0],
       ['Tata Indigo CR4', 2013, 25000, ..., 1396.0, '70', 5.0]],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

lb=LabelEncoder()
x[:,0]=lb.fit_transform(x[:,0])

lb1=LabelEncoder()
x[:,3]=lb1.fit_transform(x[:,3])

lb2=LabelEncoder()
x[:,4]=lb2.fit_transform(x[:,4])

lb3=LabelEncoder()
x[:,5]=lb3.fit_transform(x[:,5])

lb4=LabelEncoder()
x[:,6]=lb4.fit_transform(x[:,6])

lb5=LabelEncoder()
x[:,9]=lb5.fit_transform(x[:,9])
x

array([[1307, 2014, 145500, ..., 1248.0, 244, 5.0],
       [1607, 2014, 120000, ..., 1498.0, 15, 5.0],
       [385, 2006, 140000, ..., 1497.0, 253, 5.0],
       ...,
       [1319, 2009, 120000, ..., 1248.0, 241, 5.0],
       [1699, 2013, 25000, ..., 1396.0, 232, 5.0],
       [1699, 2013, 25000, ..., 1396.0, 232, 5.0]], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train

array([[710, 2015, 60000, ..., 1086.0, 226, 5.0],
       [1706, 2012, 150000, ..., 1396.0, 230, 5.0],
       [626, 2014, 110000, ..., 1396.0, 289, 5.0],
       ...,
       [714, 2009, 90000, ..., 1197.0, 255, 5.0],
       [2043, 2012, 90000, ..., 1598.0, 16, 5.0],
       [705, 2012, 110000, ..., 1086.0, 226, 5.0]], dtype=object)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=50)
regressor.fit(x_train,y_train)

RandomForestRegressor(n_estimators=50)

In [ ]:
accuracy=regressor.score(x_test,y_test)
accuracy





0.9336136833363948

In [ ]:
new_data=['Hyundai Verna 1.6 CRDI',2013,92500,'Diesel','Individual','Manual','First Owner',22.4,1588,'126.3',5]
new_data[0]=lb.transform([new_data[0]])[0]
new_data[3]=lb1.transform([new_data[3]])[0]
new_data[4]=lb2.transform([new_data[4]])[0]
new_data[5]=lb3.transform([new_data[5]])[0]
new_data[6]=lb4.transform([new_data[6]])[0]
new_data[9]=lb5.transform([new_data[9]])[0]
regressor.predict([new_data])

array([526699.98])

In [ ]:
# Support vector classification(machine SVM)

In [ ]:
import pandas as pd
data=pd.read_csv('diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
x=data.drop(['Outcome'],axis=1).values
y=data['Outcome'].values
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train.shape

(614, 8)

In [ ]:
from sklearn.svm import SVC
classifier=SVC()
classifier.fit(x_train,y_train)

SVC()

In [ ]:
accuracy=classifier.score(x_test,y_test)
accuracy

0.7922077922077922

In [ ]:
new_data=[0,	137,	40,	35	,168,	43.1,	2.288	,33	]
result=classifier.predict([new_data])
result

array([1])

In [ ]:
if (result[0]==1):
  print('diabetes')
else:
  print('no diabetes')

diabetes


In [ ]:
#support vector regressrion

import pandas as pd
data=pd.read_csv('auto-mpg.csv')
data.head()


mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [ ]:
x=data.iloc[:,1:].values
y=data.iloc[:,0].values
x[1]


array([8, 350.0, '165', 3693, 11.5, 70, 1, 'buick skylark 320'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

lb=LabelEncoder()
x[:,2]=lb.fit_transform(x[:,2])

lb1=LabelEncoder()
x[:,7]=lb1.fit_transform(x[:,7])
x

array([[8, 307.0, 15, ..., 70, 1, 49],
       [8, 350.0, 33, ..., 70, 1, 36],
       [8, 318.0, 27, ..., 70, 1, 231],
       ...,
       [4, 135.0, 78, ..., 82, 1, 119],
       [4, 120.0, 73, ..., 82, 1, 159],
       [4, 119.0, 76, ..., 82, 1, 69]], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train

array([[8, 318.0, 27, ..., 72, 1, 223],
       [4, 97.0, 55, ..., 71, 2, 286],
       [4, 97.0, 72, ..., 80, 2, 18],
       ...,
       [4, 68.0, 50, ..., 73, 2, 124],
       [6, 250.0, 0, ..., 71, 1, 243],
       [4, 90.0, 66, ..., 75, 2, 284]], dtype=object)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
x_train

array([[ 1.49526939,  1.22961301, -0.80315256, ..., -1.13752513,
        -0.73301171,  0.80959959],
       [-0.85285735, -0.92367663,  0.13817565, ..., -1.41177304,
         0.5068698 ,  1.51396917],
       [-0.85285735, -0.92367663,  0.70969634, ...,  1.05645814,
         0.5068698 , -1.48239665],
       ...,
       [-0.85285735, -1.206235  , -0.02991867, ..., -0.86327722,
         0.5068698 , -0.29726688],
       [ 0.32120602,  0.56706235, -1.7108619 , ..., -1.41177304,
        -0.73301171,  1.03320898],
       [-0.85285735, -0.99188037,  0.50798316, ..., -0.31478141,
         0.5068698 ,  1.49160823]])

In [ ]:
from sklearn.svm import SVR
regressor=SVR()
regressor.fit(x_train,y_train)

SVR()

In [ ]:
accuracy=regressor.score(x_test,y_test)
accuracy

0.8535956414670092

In [ ]:
x[3]

array([8, 304.0, 27, 3433, 12.0, 70, 1, 14], dtype=object)

In [ ]:
new_data=[8,	218.0,	'150',	4436,	15.0,	70,	1	,'buick skylark 320']

#RE lABELLING
new_data[2]=lb.transform([new_data[2]])[0]
new_data[7]=lb1.transform([new_data[7]])[0]

#RE SCALING
new_data=sc.transform([new_data])

regressor.predict(new_data)




array([15.49615512])

In [ ]:
#logistic Regression

In [ ]:
import pandas as pd
data=pd.read_csv('adult.csv')
data.tail()

age     workclass  fnlwgt   education  educational-num  \
48837   27       Private  257302  Assoc-acdm               12   
48838   40       Private  154374     HS-grad                9   
48839   58       Private  151910     HS-grad                9   
48840   22       Private  201490     HS-grad                9   
48841   52  Self-emp-inc  287927     HS-grad                9   

           marital-status         occupation relationship   race  gender  \
48837  Married-civ-spouse       Tech-support         Wife  White  Female   
48838  Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
48839             Widowed       Adm-clerical    Unmarried  White  Female   
48840       Never-married       Adm-clerical    Own-child  White    Male   
48841  Married-civ-spouse    Exec-managerial         Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income  
48837             0             0              38  United-States  <=50K  
48838             0             0              40  United-States   >50K  
48839             0             0              40  United-States  <=50K  
48840             0             0              20  United-States  <=50K  
48841         15024             0              40  United-States   >50K

In [ ]:

data['native-country']=data['native-country'].str.replace('?','United-States')
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [ ]:
x=data.iloc[:,[0,1,3,5,6,9,12,13]].values
y=data.iloc[:,-1].values
x ,y

(array([[25, 'Private', '11th', ..., 'Male', 40, 'United-States'],
        [38, 'Private', 'HS-grad', ..., 'Male', 50, 'United-States'],
        [28, 'Local-gov', 'Assoc-acdm', ..., 'Male', 40, 'United-States'],
        ...,
        [58, 'Private', 'HS-grad', ..., 'Female', 40, 'United-States'],
        [22, 'Private', 'HS-grad', ..., 'Male', 20, 'United-States'],
        [52, 'Self-emp-inc', 'HS-grad', ..., 'Female', 40,
         'United-States']], dtype=object),
 array(['<=50K', '<=50K', '>50K', ..., '<=50K', '<=50K', '>50K'],
       dtype=object))

In [ ]:
from sklearn.preprocessing import LabelEncoder

lb=LabelEncoder()
x[:,1]=lb.fit_transform(x[:,1])

lb1=LabelEncoder()
x[:,2]=lb1.fit_transform(x[:,2])

lb2=LabelEncoder()
x[:,3]=lb2.fit_transform(x[:,3])

lb3=LabelEncoder()
x[:,4]=lb3.fit_transform(x[:,4])

lb4=LabelEncoder()
x[:,5]=lb4.fit_transform(x[:,5])

lb5=LabelEncoder()
x[:,7]=lb5.fit_transform(x[:,7])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train

array([[20, 3, 15, ..., 0, 40, 38],
       [42, 3, 8, ..., 1, 52, 38],
       [35, 6, 15, ..., 0, 40, 38],
       ...,
       [55, 3, 10, ..., 1, 55, 38],
       [29, 5, 1, ..., 0, 5, 38],
       [59, 6, 12, ..., 1, 8, 38]], dtype=object)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
accuracy=classifier.score(x_test,y_test)
accuracy

0.7567816562595967

In [ ]:
from sklearn.preprocessing import LabelEncoder
import numpy as np  # Import numpy

# ... (your existing code for label encoding) ...

new_data = [40,	'Private','HS-grad'	,	'Married-civ-spouse'	,'Machine-op-inspct',	'Male',	40	,'United-States']

# Convert new_data to a list of lists before transformation
new_data_transformed = [
    [new_data[0]],
    [new_data[1]],
    [new_data[2]],
    [new_data[3]],
    [new_data[4]],
    [new_data[5]],
    [new_data[6]],
    [new_data[7]]
]

# Perform label encoding on each feature individually
new_data_transformed[1] = lb.transform(new_data_transformed[1])
new_data_transformed[2] = lb1.transform(new_data_transformed[2])
new_data_transformed[3] = lb2.transform(new_data_transformed[3])
new_data_transformed[4] = lb3.transform(new_data_transformed[4])
new_data_transformed[5] = lb4.transform(new_data_transformed[5])
new_data_transformed[7] = lb5.transform(new_data_transformed[7])

# Flatten the list of lists and convert to numpy array
new_data_transformed = np.array([item for sublist in new_data_transformed for item in sublist])


# Now, predict using the transformed data
classifier.predict([new_data_transformed]) # Pass as a list with single element.

array(['<=50K'], dtype=object)

In [ ]:
# KNN Neihbourhood

import pandas as pd
data=pd.read_csv('Iris.csv')
data.iloc[10:15]
#data['Species'].value_counts()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa

In [ ]:
x=data.iloc[:,1:5].values
y=data.iloc[:,5].values


In [ ]:
from sklearn.preprocessing import LabelBinarizer
lb=LabelBinarizer()
y=lb.fit_transform(y)


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
classifier.score(x_test,y_test)

0.9666666666666667

In [ ]:
new_data=[4.8,	3.0,	1.4	,0.1]
classifier.predict([new_data])

#100 ---setosa
#001----viginica
#010----versicolor




array([[1, 0, 0]])

In [2]:
#Navies Bayes

import pandas as pd
data=pd.read_csv('Social_Network_Ads.csv')
data.tail()

User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [7]:
x=data.iloc[:,[1,2,3]].values
y=data.iloc[:,4].values


In [8]:
from sklearn.preprocessing import LabelEncoder

lb=LabelEncoder()
x[:,0]=lb.fit_transform(x[:,0])


In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [12]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [13]:
accuracy=classifier.score(x_test,y_test)
accuracy

0.925

In [20]:
new_data=['Male'	,49,	76000		]
new_data[0]=lb.transform([new_data[0]])[0]
classifier.predict([new_data])


array([1])

In [16]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0